import type { ChatChannel, ChatMessage, Meeting, TeamMember } from "./types";

const now = Date.now();
const min = (m: number) => new Date(now + m * 60000).toISOString();

export const seedMembers: TeamMember[] = [
  {
    id: "m-priya",
    name: "Priya Nair",
    role: "Delivery lead",
    email: "priya@flowdesk.io",
    portal: "team",
    status: "online",
    color: "#12a594",
  },
  {
    id: "m-marcus",
    name: "Marcus Hale",
    role: "Product designer",
    email: "marcus@flowdesk.io",
    portal: "team",
    status: "online",
    color: "#4f7df3",
  },
  {
    id: "m-sofia",
    name: "Sofia Lindqvist",
    role: "Backend engineer",
    email: "sofia@flowdesk.io",
    portal: "team",
    status: "away",
    color: "#e0912f",
  },
  {
    id: "m-elena",
    name: "Elena Fischer",
    role: "Client stakeholder",
    email: "client@demo.com",
    portal: "client",
    status: "online",
    color: "#7b5ea7",
  },
  {
    id: "m-ravi",
    name: "Ravi Menon",
    role: "Workspace admin",
    email: "admin@demo.com",
    portal: "admin",
    status: "offline",
    color: "#d1495b",
  },
];

export const seedChannels: ChatChannel[] = [
  {
    id: "ch-delivery",
    name: "Delivery standup",
    kind: "group",
    roomType: "task" as const,
    members: ["m-priya", "m-marcus", "m-sofia", "m-ravi"],
    portals: ["team", "admin"],
  },
  {
    id: "ch-northwind",
    name: "Northwind Labs — Client room",
    kind: "group",
    roomType: "client" as const,
    members: ["m-priya", "m-elena", "m-ravi"],
    portals: ["client", "team", "admin"],
  },
  {
    id: "ch-billing",
    name: "TSK-1001 · Billing queue",
    kind: "group",
    roomType: "task" as const,
    members: ["m-priya", "m-sofia"],
    taskId: "TSK-1001",
    portals: ["team", "admin"],
  },
  {
    id: "ch-dm-priya",
    name: "Priya Nair",
    kind: "direct",
    roomType: "dm" as const,
    members: ["m-priya"],
    portals: ["client", "team", "admin"],
  },
  {
    id: "ch-dm-marcus",
    name: "Marcus Hale",
    kind: "direct",
    roomType: "dm" as const,
    members: ["m-marcus"],
    portals: ["client", "team", "admin"],
  },
];

export const seedMessages: ChatMessage[] = [
  {
    id: "msg-1",
    channelId: "ch-delivery",
    authorId: "m-priya",
    authorName: "Priya Nair",
    body: "Standup in 10. Please move blocked items to the review column first.",
    at: min(-180),
    read: true,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-2",
    channelId: "ch-delivery",
    authorId: "m-sofia",
    authorName: "Sofia Lindqvist",
    body: "Billing queue retries are deployed to staging — TSK-1001 needs QA.",
    at: min(-42),
    read: false,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-3",
    channelId: "ch-northwind",
    authorId: "m-elena",
    authorName: "Elena Fischer",
    body: "Can we get the dashboard refresh preview before Friday?",
    at: min(-95),
    read: false,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-4",
    channelId: "ch-northwind",
    authorId: "m-priya",
    authorName: "Priya Nair",
    body: "Yes — Marcus is polishing the KPI cards today.",
    at: min(-88),
    read: true,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-5",
    channelId: "ch-billing",
    authorId: "m-sofia",
    authorName: "Sofia Lindqvist",
    body: "Added exponential backoff, max 5 retries. Logging to the sync audit trail.",
    at: min(-25),
    read: false,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-6",
    channelId: "ch-dm-priya",
    authorId: "m-priya",
    authorName: "Priya Nair",
    body: "Ping me if the ClickUp sync throws duplicates again.",
    at: min(-12),
    read: false,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
  {
    id: "msg-7",
    channelId: "ch-dm-marcus",
    authorId: "m-marcus",
    authorName: "Marcus Hale",
    body: "Shared the new activity rail spec in the task thread.",
    at: min(-320),
    read: true,
    kind: "text" as const,
    reactions: [],
    receipt: "read" as const,
  },
];

export const seedMeetings: Meeting[] = [
  {
    id: "mt-1",
    title: "Sprint 24 planning",
    agenda: "Scope the billing queue rollout and portal design refresh.",
    startsAt: min(45),
    durationMins: 45,
    host: "Priya Nair",
    attendees: ["m-priya", "m-marcus", "m-sofia"],
    link: "https://meet.flowdesk.io/sprint-24",
    status: "scheduled",
    portals: ["team", "admin"],
  },
  {
    id: "mt-2",
    title: "Northwind weekly sync",
    agenda: "Delivery status, blockers and next milestone sign-off.",
    startsAt: min(-15),
    durationMins: 30,
    host: "Elena Fischer",
    attendees: ["m-elena", "m-priya", "m-ravi"],
    link: "https://meet.flowdesk.io/northwind-weekly",
    status: "live",
    portals: ["client", "team", "admin"],
  },
  {
    id: "mt-3",
    title: "Quarterly access review",
    agenda: "Audit roles, ClickUp tokens and workspace permissions.",
    startsAt: min(2880),
    durationMins: 60,
    host: "Ravi Menon",
    attendees: ["m-ravi", "m-priya"],
    link: "https://meet.flowdesk.io/access-review",
    status: "scheduled",
    portals: ["admin"],
  },
  {
    id: "mt-4",
    title: "Design critique",
    agenda: "Review KPI card variants for the client dashboard.",
    startsAt: min(-2880),
    durationMins: 40,
    host: "Marcus Hale",
    attendees: ["m-marcus", "m-priya", "m-elena"],
    link: "https://meet.flowdesk.io/design-critique",
    status: "completed",
    portals: ["client", "team", "admin"],
  },
];
