/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as AdminLoginRouteImport } from './routes/admin.login'
import { Route as ClientLoginRouteImport } from './routes/client.login'
import { Route as ClientSignupRouteImport } from './routes/client.signup'
import { Route as PortalPortalRouteImport } from './routes/portal.$portal'
import { Route as TeamLoginRouteImport } from './routes/team.login'
import { Route as ApiPublicTaskNotifyRouteImport } from './routes/api.public.task-notify'
import { Route as ApiZoomWebhookRouteImport } from './routes/api.zoom.webhook'
import { Route as PortalPortalIndexRouteImport } from './routes/portal.$portal.index'
import { Route as PortalPortalActivityRouteImport } from './routes/portal.$portal.activity'
import { Route as PortalPortalAnalyticsRouteImport } from './routes/portal.$portal.analytics'
import { Route as PortalPortalIntegrationsRouteImport } from './routes/portal.$portal.integrations'
import { Route as PortalPortalMeetingsRouteImport } from './routes/portal.$portal.meetings'
import { Route as PortalPortalMessagesRouteImport } from './routes/portal.$portal.messages'
import { Route as PortalPortalPeopleRouteImport } from './routes/portal.$portal.people'
import { Route as PortalPortalSettingsRouteImport } from './routes/portal.$portal.settings'
import { Route as PortalPortalTasksRouteImport } from './routes/portal.$portal.tasks'
import { Route as ApiPublicClickupMapUsersRouteImport } from './routes/api.public.clickup.map-users'
import { Route as ApiPublicClickupPushRouteImport } from './routes/api.public.clickup.push'
import { Route as ApiPublicClickupRegisterWebhookRouteImport } from './routes/api.public.clickup.register-webhook'
import { Route as ApiPublicClickupWebhookRouteImport } from './routes/api.public.clickup.webhook'
import { Route as ApiPublicZoomWebhookRouteImport } from './routes/api.public.zoom.webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminLoginRoute = AdminLoginRouteImport.update({
  id: '/admin/login',
  path: '/admin/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientLoginRoute = ClientLoginRouteImport.update({
  id: '/client/login',
  path: '/client/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ClientSignupRoute = ClientSignupRouteImport.update({
  id: '/client/signup',
  path: '/client/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalRoute = PortalPortalRouteImport.update({
  id: '/portal/$portal',
  path: '/portal/$portal',
  getParentRoute: () => rootRouteImport,
} as any)
const TeamLoginRoute = TeamLoginRouteImport.update({
  id: '/team/login',
  path: '/team/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicTaskNotifyRoute = ApiPublicTaskNotifyRouteImport.update({
  id: '/api/public/task-notify',
  path: '/api/public/task-notify',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiZoomWebhookRoute = ApiZoomWebhookRouteImport.update({
  id: '/api/zoom/webhook',
  path: '/api/zoom/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const PortalPortalIndexRoute = PortalPortalIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalActivityRoute = PortalPortalActivityRouteImport.update({
  id: '/activity',
  path: '/activity',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalAnalyticsRoute = PortalPortalAnalyticsRouteImport.update({
  id: '/analytics',
  path: '/analytics',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalIntegrationsRoute =
  PortalPortalIntegrationsRouteImport.update({
    id: '/integrations',
    path: '/integrations',
    getParentRoute: () => PortalPortalRoute,
  } as any)
const PortalPortalMeetingsRoute = PortalPortalMeetingsRouteImport.update({
  id: '/meetings',
  path: '/meetings',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalMessagesRoute = PortalPortalMessagesRouteImport.update({
  id: '/messages',
  path: '/messages',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalPeopleRoute = PortalPortalPeopleRouteImport.update({
  id: '/people',
  path: '/people',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalSettingsRoute = PortalPortalSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => PortalPortalRoute,
} as any)
const PortalPortalTasksRoute = PortalPortalTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => PortalPortalRoute,
} as any)
const ApiPublicClickupMapUsersRoute =
  ApiPublicClickupMapUsersRouteImport.update({
    id: '/api/public/clickup/map-users',
    path: '/api/public/clickup/map-users',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClickupPushRoute = ApiPublicClickupPushRouteImport.update({
  id: '/api/public/clickup/push',
  path: '/api/public/clickup/push',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicClickupRegisterWebhookRoute =
  ApiPublicClickupRegisterWebhookRouteImport.update({
    id: '/api/public/clickup/register-webhook',
    path: '/api/public/clickup/register-webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicClickupWebhookRoute = ApiPublicClickupWebhookRouteImport.update({
  id: '/api/public/clickup/webhook',
  path: '/api/public/clickup/webhook',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicZoomWebhookRoute = ApiPublicZoomWebhookRouteImport.update({
  id: '/api/public/zoom/webhook',
  path: '/api/public/zoom/webhook',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/portal/$portal': typeof PortalPortalRouteWithChildren
  '/team/login': typeof TeamLoginRoute
  '/api/public/task-notify': typeof ApiPublicTaskNotifyRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/portal/$portal/activity': typeof PortalPortalActivityRoute
  '/portal/$portal/analytics': typeof PortalPortalAnalyticsRoute
  '/portal/$portal/integrations': typeof PortalPortalIntegrationsRoute
  '/portal/$portal/meetings': typeof PortalPortalMeetingsRoute
  '/portal/$portal/messages': typeof PortalPortalMessagesRoute
  '/portal/$portal/people': typeof PortalPortalPeopleRoute
  '/portal/$portal/settings': typeof PortalPortalSettingsRoute
  '/portal/$portal/tasks': typeof PortalPortalTasksRoute
  '/portal/$portal/': typeof PortalPortalIndexRoute
  '/api/public/clickup/map-users': typeof ApiPublicClickupMapUsersRoute
  '/api/public/clickup/push': typeof ApiPublicClickupPushRoute
  '/api/public/clickup/register-webhook': typeof ApiPublicClickupRegisterWebhookRoute
  '/api/public/clickup/webhook': typeof ApiPublicClickupWebhookRoute
  '/api/public/zoom/webhook': typeof ApiPublicZoomWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/team/login': typeof TeamLoginRoute
  '/api/public/task-notify': typeof ApiPublicTaskNotifyRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/portal/$portal/activity': typeof PortalPortalActivityRoute
  '/portal/$portal/analytics': typeof PortalPortalAnalyticsRoute
  '/portal/$portal/integrations': typeof PortalPortalIntegrationsRoute
  '/portal/$portal/meetings': typeof PortalPortalMeetingsRoute
  '/portal/$portal/messages': typeof PortalPortalMessagesRoute
  '/portal/$portal/people': typeof PortalPortalPeopleRoute
  '/portal/$portal/settings': typeof PortalPortalSettingsRoute
  '/portal/$portal/tasks': typeof PortalPortalTasksRoute
  '/portal/$portal': typeof PortalPortalIndexRoute
  '/api/public/clickup/map-users': typeof ApiPublicClickupMapUsersRoute
  '/api/public/clickup/push': typeof ApiPublicClickupPushRoute
  '/api/public/clickup/register-webhook': typeof ApiPublicClickupRegisterWebhookRoute
  '/api/public/clickup/webhook': typeof ApiPublicClickupWebhookRoute
  '/api/public/zoom/webhook': typeof ApiPublicZoomWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/signup': typeof SignupRoute
  '/admin/login': typeof AdminLoginRoute
  '/client/login': typeof ClientLoginRoute
  '/client/signup': typeof ClientSignupRoute
  '/portal/$portal': typeof PortalPortalRouteWithChildren
  '/team/login': typeof TeamLoginRoute
  '/api/public/task-notify': typeof ApiPublicTaskNotifyRoute
  '/api/zoom/webhook': typeof ApiZoomWebhookRoute
  '/portal/$portal/activity': typeof PortalPortalActivityRoute
  '/portal/$portal/analytics': typeof PortalPortalAnalyticsRoute
  '/portal/$portal/integrations': typeof PortalPortalIntegrationsRoute
  '/portal/$portal/meetings': typeof PortalPortalMeetingsRoute
  '/portal/$portal/messages': typeof PortalPortalMessagesRoute
  '/portal/$portal/people': typeof PortalPortalPeopleRoute
  '/portal/$portal/settings': typeof PortalPortalSettingsRoute
  '/portal/$portal/tasks': typeof PortalPortalTasksRoute
  '/portal/$portal/': typeof PortalPortalIndexRoute
  '/api/public/clickup/map-users': typeof ApiPublicClickupMapUsersRoute
  '/api/public/clickup/push': typeof ApiPublicClickupPushRoute
  '/api/public/clickup/register-webhook': typeof ApiPublicClickupRegisterWebhookRoute
  '/api/public/clickup/webhook': typeof ApiPublicClickupWebhookRoute
  '/api/public/zoom/webhook': typeof ApiPublicZoomWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/client/login'
    | '/client/signup'
    | '/portal/$portal'
    | '/team/login'
    | '/api/public/task-notify'
    | '/api/zoom/webhook'
    | '/portal/$portal/activity'
    | '/portal/$portal/analytics'
    | '/portal/$portal/integrations'
    | '/portal/$portal/meetings'
    | '/portal/$portal/messages'
    | '/portal/$portal/people'
    | '/portal/$portal/settings'
    | '/portal/$portal/tasks'
    | '/portal/$portal/'
    | '/api/public/clickup/map-users'
    | '/api/public/clickup/push'
    | '/api/public/clickup/register-webhook'
    | '/api/public/clickup/webhook'
    | '/api/public/zoom/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/client/login'
    | '/client/signup'
    | '/team/login'
    | '/api/public/task-notify'
    | '/api/zoom/webhook'
    | '/portal/$portal/activity'
    | '/portal/$portal/analytics'
    | '/portal/$portal/integrations'
    | '/portal/$portal/meetings'
    | '/portal/$portal/messages'
    | '/portal/$portal/people'
    | '/portal/$portal/settings'
    | '/portal/$portal/tasks'
    | '/portal/$portal'
    | '/api/public/clickup/map-users'
    | '/api/public/clickup/push'
    | '/api/public/clickup/register-webhook'
    | '/api/public/clickup/webhook'
    | '/api/public/zoom/webhook'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/reset-password'
    | '/signup'
    | '/admin/login'
    | '/client/login'
    | '/client/signup'
    | '/portal/$portal'
    | '/team/login'
    | '/api/public/task-notify'
    | '/api/zoom/webhook'
    | '/portal/$portal/activity'
    | '/portal/$portal/analytics'
    | '/portal/$portal/integrations'
    | '/portal/$portal/meetings'
    | '/portal/$portal/messages'
    | '/portal/$portal/people'
    | '/portal/$portal/settings'
    | '/portal/$portal/tasks'
    | '/portal/$portal/'
    | '/api/public/clickup/map-users'
    | '/api/public/clickup/push'
    | '/api/public/clickup/register-webhook'
    | '/api/public/clickup/webhook'
    | '/api/public/zoom/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SignupRoute: typeof SignupRoute
  AdminLoginRoute: typeof AdminLoginRoute
  ClientLoginRoute: typeof ClientLoginRoute
  ClientSignupRoute: typeof ClientSignupRoute
  PortalPortalRoute: typeof PortalPortalRouteWithChildren
  TeamLoginRoute: typeof TeamLoginRoute
  ApiPublicTaskNotifyRoute: typeof ApiPublicTaskNotifyRoute
  ApiZoomWebhookRoute: typeof ApiZoomWebhookRoute
  ApiPublicClickupMapUsersRoute: typeof ApiPublicClickupMapUsersRoute
  ApiPublicClickupPushRoute: typeof ApiPublicClickupPushRoute
  ApiPublicClickupRegisterWebhookRoute: typeof ApiPublicClickupRegisterWebhookRoute
  ApiPublicClickupWebhookRoute: typeof ApiPublicClickupWebhookRoute
  ApiPublicZoomWebhookRoute: typeof ApiPublicZoomWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/login': {
      id: '/admin/login'
      path: '/admin/login'
      fullPath: '/admin/login'
      preLoaderRoute: typeof AdminLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/login': {
      id: '/client/login'
      path: '/client/login'
      fullPath: '/client/login'
      preLoaderRoute: typeof ClientLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/client/signup': {
      id: '/client/signup'
      path: '/client/signup'
      fullPath: '/client/signup'
      preLoaderRoute: typeof ClientSignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$portal': {
      id: '/portal/$portal'
      path: '/portal/$portal'
      fullPath: '/portal/$portal'
      preLoaderRoute: typeof PortalPortalRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/team/login': {
      id: '/team/login'
      path: '/team/login'
      fullPath: '/team/login'
      preLoaderRoute: typeof TeamLoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/task-notify': {
      id: '/api/public/task-notify'
      path: '/api/public/task-notify'
      fullPath: '/api/public/task-notify'
      preLoaderRoute: typeof ApiPublicTaskNotifyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/zoom/webhook': {
      id: '/api/zoom/webhook'
      path: '/api/zoom/webhook'
      fullPath: '/api/zoom/webhook'
      preLoaderRoute: typeof ApiZoomWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/portal/$portal/': {
      id: '/portal/$portal/'
      path: '/'
      fullPath: '/portal/$portal/'
      preLoaderRoute: typeof PortalPortalIndexRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/activity': {
      id: '/portal/$portal/activity'
      path: '/activity'
      fullPath: '/portal/$portal/activity'
      preLoaderRoute: typeof PortalPortalActivityRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/analytics': {
      id: '/portal/$portal/analytics'
      path: '/analytics'
      fullPath: '/portal/$portal/analytics'
      preLoaderRoute: typeof PortalPortalAnalyticsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/integrations': {
      id: '/portal/$portal/integrations'
      path: '/integrations'
      fullPath: '/portal/$portal/integrations'
      preLoaderRoute: typeof PortalPortalIntegrationsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/meetings': {
      id: '/portal/$portal/meetings'
      path: '/meetings'
      fullPath: '/portal/$portal/meetings'
      preLoaderRoute: typeof PortalPortalMeetingsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/messages': {
      id: '/portal/$portal/messages'
      path: '/messages'
      fullPath: '/portal/$portal/messages'
      preLoaderRoute: typeof PortalPortalMessagesRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/people': {
      id: '/portal/$portal/people'
      path: '/people'
      fullPath: '/portal/$portal/people'
      preLoaderRoute: typeof PortalPortalPeopleRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/settings': {
      id: '/portal/$portal/settings'
      path: '/settings'
      fullPath: '/portal/$portal/settings'
      preLoaderRoute: typeof PortalPortalSettingsRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/portal/$portal/tasks': {
      id: '/portal/$portal/tasks'
      path: '/tasks'
      fullPath: '/portal/$portal/tasks'
      preLoaderRoute: typeof PortalPortalTasksRouteImport
      parentRoute: typeof PortalPortalRoute
    }
    '/api/public/clickup/map-users': {
      id: '/api/public/clickup/map-users'
      path: '/api/public/clickup/map-users'
      fullPath: '/api/public/clickup/map-users'
      preLoaderRoute: typeof ApiPublicClickupMapUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clickup/push': {
      id: '/api/public/clickup/push'
      path: '/api/public/clickup/push'
      fullPath: '/api/public/clickup/push'
      preLoaderRoute: typeof ApiPublicClickupPushRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clickup/register-webhook': {
      id: '/api/public/clickup/register-webhook'
      path: '/api/public/clickup/register-webhook'
      fullPath: '/api/public/clickup/register-webhook'
      preLoaderRoute: typeof ApiPublicClickupRegisterWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/clickup/webhook': {
      id: '/api/public/clickup/webhook'
      path: '/api/public/clickup/webhook'
      fullPath: '/api/public/clickup/webhook'
      preLoaderRoute: typeof ApiPublicClickupWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/zoom/webhook': {
      id: '/api/public/zoom/webhook'
      path: '/api/public/zoom/webhook'
      fullPath: '/api/public/zoom/webhook'
      preLoaderRoute: typeof ApiPublicZoomWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface PortalPortalRouteChildren {
  PortalPortalActivityRoute: typeof PortalPortalActivityRoute
  PortalPortalAnalyticsRoute: typeof PortalPortalAnalyticsRoute
  PortalPortalIntegrationsRoute: typeof PortalPortalIntegrationsRoute
  PortalPortalMeetingsRoute: typeof PortalPortalMeetingsRoute
  PortalPortalMessagesRoute: typeof PortalPortalMessagesRoute
  PortalPortalPeopleRoute: typeof PortalPortalPeopleRoute
  PortalPortalSettingsRoute: typeof PortalPortalSettingsRoute
  PortalPortalTasksRoute: typeof PortalPortalTasksRoute
  PortalPortalIndexRoute: typeof PortalPortalIndexRoute
}

const PortalPortalRouteChildren: PortalPortalRouteChildren = {
  PortalPortalActivityRoute: PortalPortalActivityRoute,
  PortalPortalAnalyticsRoute: PortalPortalAnalyticsRoute,
  PortalPortalIntegrationsRoute: PortalPortalIntegrationsRoute,
  PortalPortalMeetingsRoute: PortalPortalMeetingsRoute,
  PortalPortalMessagesRoute: PortalPortalMessagesRoute,
  PortalPortalPeopleRoute: PortalPortalPeopleRoute,
  PortalPortalSettingsRoute: PortalPortalSettingsRoute,
  PortalPortalTasksRoute: PortalPortalTasksRoute,
  PortalPortalIndexRoute: PortalPortalIndexRoute,
}

const PortalPortalRouteWithChildren = PortalPortalRoute._addFileChildren(
  PortalPortalRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SignupRoute: SignupRoute,
  AdminLoginRoute: AdminLoginRoute,
  ClientLoginRoute: ClientLoginRoute,
  ClientSignupRoute: ClientSignupRoute,
  PortalPortalRoute: PortalPortalRouteWithChildren,
  TeamLoginRoute: TeamLoginRoute,
  ApiPublicTaskNotifyRoute: ApiPublicTaskNotifyRoute,
  ApiZoomWebhookRoute: ApiZoomWebhookRoute,
  ApiPublicClickupMapUsersRoute: ApiPublicClickupMapUsersRoute,
  ApiPublicClickupPushRoute: ApiPublicClickupPushRoute,
  ApiPublicClickupRegisterWebhookRoute: ApiPublicClickupRegisterWebhookRoute,
  ApiPublicClickupWebhookRoute: ApiPublicClickupWebhookRoute,
  ApiPublicZoomWebhookRoute: ApiPublicZoomWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
